clusterTemplate:
  capiVersion: capi-v5
  version: v1.31.0-1.0.0

clusterConfig:
  endpointAccess:
    public: true
    publicCIDRs: ["0.0.0.0/0"]
  additionaSecurityGroup: capi-cm-poc-node-20250625000420831600000008
  amiType: AL2_x86_64
  diskSize: 250
  systemNodeType: m5.xlarge
  systemNodeReplicas: 1
  systemNodeScaling:
    minSize: 1
    maxSize: 30
  userNodeType: m5.xlarge
  userNodeReplicas: 1
  userNodeScaling:
    minSize: 1
    maxSize: 30
  additionalTags:
    application: ""
    group: ""
    organization: "engineering"
    stack: ""
    team: ""
    email: "kubesources.com"
    vpEmail: "kubesources.com"
  iamAccessRoleNames: gitlab-runner-provisioner-role
