clusterTemplate:
  capiVersion: capi-v5
  version: v1.31.0-1.0.0

clusterConfig:
  clusterRegion: us-east-1
  endpointAccess:
    public: true
    publicCIDRs: "0.0.0.0/0"
  additionalSecurityGroup: sg-0cff719475cd771e4 #capi-shared-sg - depending on vpc
  # adminAccessRoleNames: "gitlab-runner-provisioner-role,whatever"
  adminAccessRoleNames: "gitlab-runner-provisioner-role"
  additionalTags:
    application: capi-downstream-poc
    group: engineering
    organization: engineering
    stack: phoeengineeringnix
    team: engineering
    email: kubesources.com
    vpEmail: kubesources.com
    app_id: NA
    app_ref_id:
    cost_code: NA
    data_priv: NA
    ops_owner: kubesources.com
    sec_owner: kubesources.com
    dev_owner: kubesources.com

  customizations: "KEDA"

  systemNode:
    type: m5.xlarge
    replicas: 1
    autoscaling:
      minSize: 1
      maxSize: 30

  userNode:
    type: m5.xlarge
    replicas: 1
    autoscaling:
      minSize: 1
      maxSize: 30
  diskSize: 250

aws:
  region: us-east-1
  availabilityZones: "us-east-1a,us-east-1b"
  networking:
    vpcId: vpc-00b26597f26ccd886
    publicSubnets: "subnet-0ba740ba10176793b,subnet-0e35eb24f2c102cc8"
    privateSubnets: "subnet-099cb17c558827f11,subnet-0eb9f8dc4b07aaebd"
    intraSubnets: "subnet-0f8e0161edef452b6,subnet-0bcf604fb5c773afc"
