clusterTemplate:
  capiVersion: capi-v5
  version: v1.31.0-1.0.0

clusterConfig:
  clusterRegion: us-east-1
  endpointAccess:
    public: true
    publicCIDRs: "0.0.0.0/0"
  additionaSecurityGroup: sg-089188b61b545498e #capi-shared-sg
  adminAccessRoleNames: "gitlab-runner-provisioner-role,whatever"
  additionalTags:
    application: capi-downstream-poc
    group: engineering
    organization: engineering
    stack: phoeengineeringnix
    team: engineering
    email: kubesources.com
    vpEmail: kubesources.com
    app_id: NA
    app_ref_id: NA
    cost_code: NA
    data_priv: NA
    ops_owner: kubesources.com
    sec_owner: kubesources.com
    dev_owner: kubesources.com

  customizations: "KEDA"
  amiType: AL2_x86_64
  diskSize: 250
  systemNodeType: m5.xlarge
  systemNodeReplicas: 1
  systemNodeScaling:
    minSize: 1
    maxSize: 30
  userNodeType: m5.xlarge
  userNodeReplicas: 1
  userNodeScaling:
    minSize: 1
    maxSize: 30

aws:
  region: us-east-1
  networking:
    vpcId: vpc-04c76c355e6c7d395
    publicSubnets: "subnet-0cf9753f264b15813,subnet-01859952eaa7295ee"
    privateSubnets: "subnet-0f3c87138547be048,subnet-07795a170e35ac68a"
    intraSubnets: "subnet-0f7284d81ddb3229f,subnet-0651567f40cf51151"
